spring.application.name=MonikaMart

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/monikamart
spring.datasource.username=root
spring.datasource.password=Monika@2008


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080